/*
 * This source file was generated by the Gradle 'init' task
 */

public class RecipeCalculator
{
    public String getGreeting()
    {
        return "Gello Gorld!";
    }

    public static void main(String[] args)
    {
        System.out.println(new RecipeCalculator().getGreeting());
    }
}
