/*
 * This source file was generated by the Gradle 'init' task
 */

import containers.*;

import java.util.ArrayList;

public class RecipeCalculator
{
    public static void main(String[] args)
    {
        // Constructing *the book*
        RecipeBook recipe_book = new RecipeBook();

        ArrayList<String> recipe = new ArrayList<String>();

        recipe.add("stick x2");
        recipe.add("wooden plank x3");

        recipe_book.addRecipe("wooden pickaxe", recipe);

        System.out.println(recipe_book.toString());
    }
}
