/*
 * This source file was generated by the Gradle 'init' task
 */

package containers;

//import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;


class ItemTest
{
    /*@Test void defaultItem()
    {
        Item itemToTest = new Item();
        
        assertEquals(itemToTest.getId(), "INVALID ITEM");
        assertNull(itemToTest.getIngredients());
        assertTrue(itemToTest.isBase());
    }

    @Test void itemWithId()
    {
        Item itemToTest = new Item("dirt");
        
        assertEquals(itemToTest.getId(), "dirt");
        assertNull(itemToTest.getIngredients());
        assertTrue(itemToTest.isBase());
    }

    @Test void itemWithBlankId()
    {
        Item itemToTest = new Item("");
        
        assertEquals(itemToTest.getId(), "");
        assertNull(itemToTest.getIngredients());
        assertTrue(itemToTest.isBase());
    }

    @Test void itemWithIngredients()
    {
        String[] ingredients = new String[2];
        ingredients[0] = "apples";
        ingredients[1] = "bananas";

        Item itemToTest = new Item("dirt", ingredients);
        
        assertEquals(itemToTest.getId(), "dirt");
        assertArrayEquals(itemToTest.getIngredients(), ingredients);
        assertNotSame(itemToTest.getIngredients(), ingredients);
        assertFalse(itemToTest.isBase());
    }*/
}
